import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SchumacherProductImage } from "@/components/schumacher-product-image";
import { SchumacherInquiry } from "@/components/schumacher-inquiry";
import { BreadcrumbJsonLd } from "@/components/json-ld";
import { getSchumacherProduct, SCHUMACHER_PRODUCTS } from "@/lib/schumacher-products";
import { SITE } from "@/lib/data";

type Params = Promise<{ slug: string }>;
export function generateStaticParams() { return SCHUMACHER_PRODUCTS.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const p = getSchumacherProduct((await params).slug); if (!p) return {}; return { title: `${p.name} by Schumacher | Fabric & Wallpaper Charleston`, description: `Explore ${p.name} by Schumacher. Request a memo, availability check and direct trade-partner quote from Charleston Decorative Arts.`, alternates: { canonical: `/schumacher/${p.slug}` } }; }

export default async function SchumacherProductPage({ params }: { params: Params }) {
  const p = getSchumacherProduct((await params).slug); if (!p) notFound();
  const schema = { "@context": "https://schema.org", "@type": "Product", name: p.name, brand: { "@type": "Brand", name: "Schumacher" }, category: p.categories.join(" and "), description: p.summary, ...(p.image ? { image: p.image } : {}), offers: { "@type": "Offer", url: `${SITE.url}/contact?schumacher=${p.slug}`, availability: "https://schema.org/InStock", priceSpecification: { "@type": "PriceSpecification", description: "Contact Charleston Decorative Arts for current availability and best available project pricing." } } };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <BreadcrumbJsonLd items={[{ name: "Home", url: SITE.url }, { name: "Schumacher", url: `${SITE.url}/schumacher` }, { name: p.name, url: `${SITE.url}/schumacher/${p.slug}` }]} />
    <article className="px-6 py-16 md:py-24"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2 md:gap-16"><div className="relative aspect-[4/5] overflow-hidden bg-[#e9dfcd]"><SchumacherProductImage product={p} priority /></div><div className="md:pt-8"><p className="text-xs uppercase tracking-[0.2em] text-[#8a6d1d]"><Link href="/luxury-wallcoverings" className="underline">Luxury Wallcoverings</Link> · <Link href="/schumacher" className="underline">Schumacher</Link></p><p className="mt-8 text-xs font-semibold uppercase tracking-[0.3em] text-[#8a6d1d]">{p.categories.join(" · ")}</p><h1 className="mt-4 font-serif text-4xl leading-tight text-[#3d2b1f] md:text-6xl">{p.name}</h1><p className="mt-6 text-lg leading-relaxed text-[#5a4632]">{p.summary}</p><p className="mt-5 border-l-2 border-[#c9a959] pl-5 text-sm italic leading-relaxed text-[#5a4632]">{p.evidence}</p><dl className="mt-9 grid grid-cols-2 border-t border-[#e4d9c2] text-sm text-[#5a4632]"><div className="border-b border-[#e4d9c2] py-4 pr-4"><dt className="text-[10px] font-semibold uppercase tracking-widest text-[#3d2b1f]">Best suited to</dt><dd className="mt-2 capitalize">{p.rooms.join(", ")}</dd></div><div className="border-b border-[#e4d9c2] py-4"><dt className="text-[10px] font-semibold uppercase tracking-widest text-[#3d2b1f]">Design character</dt><dd className="mt-2 capitalize">{p.styles.join(", ")}</dd></div><div className="border-b border-[#e4d9c2] py-4 pr-4"><dt className="text-[10px] font-semibold uppercase tracking-widest text-[#3d2b1f]">Memo & stock</dt><dd className="mt-2">Available by request</dd></div><div className="border-b border-[#e4d9c2] py-4"><dt className="text-[10px] font-semibold uppercase tracking-widest text-[#3d2b1f]">Ordering</dt><dd className="mt-2">Direct through CDA</dd></div></dl><Link href={`/contact?schumacher=${p.slug}`} className="mt-9 inline-block bg-[#8a6d1d] px-7 py-4 text-xs font-semibold uppercase tracking-widest text-[#fbf6ec] hover:bg-[#6f5717]">Request Memo & Quote</Link>{p.itemNumber && <p className="mt-5 text-xs text-[#75604a]">Featured colorway reference: Schumacher item {p.itemNumber}. Final color and specifications must be confirmed by physical memo.</p>}</div></div></article>
    <SchumacherInquiry pattern={p.name} />
    <section className="px-6 pb-24"><div className="mx-auto max-w-3xl"><h2 className="font-serif text-3xl text-[#3d2b1f]">Specifying {p.name}</h2><h3 className="mt-8 font-serif text-xl text-[#3d2b1f]">How should I select a colorway?</h3><p className="mt-2 leading-relaxed text-[#5a4632]">Request the colorways you are considering and view physical memos in the intended room. Screens cannot reliably reproduce textile color, surface texture or sheen.</p><h3 className="mt-7 font-serif text-xl text-[#3d2b1f]">How much should I order?</h3><p className="mt-2 leading-relaxed text-[#5a4632]">Quantity depends on repeat, match, wall dimensions, openings and layout. CDA can review measurements and add an appropriate reserve for pattern matching and future repairs.</p><h3 className="mt-7 font-serif text-xl text-[#3d2b1f]">Why confirm availability?</h3><p className="mt-2 leading-relaxed text-[#5a4632]">Fabric and wallcovering stock, dye lots, print runs, minimum quantities and freight can change. We verify these details before finalizing your order.</p></div></section>
  </>;
}
