import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/page-hero";
import { SchumacherProductImage } from "@/components/schumacher-product-image";
import { SchumacherInquiry } from "@/components/schumacher-inquiry";
import { BreadcrumbJsonLd } from "@/components/json-ld";
import { SCHUMACHER_PRODUCTS } from "@/lib/schumacher-products";
import { SITE } from "@/lib/data";

export const metadata: Metadata = { title: "Schumacher Fabric & Wallpaper in Charleston, SC", description: "Explore a curated Schumacher fabric and wallcovering showroom. Request memos, availability and direct trade-partner pricing from Charleston Decorative Arts.", alternates: { canonical: "/schumacher" } };

export default function SchumacherPage() {
  const schema = { "@context": "https://schema.org", "@type": "CollectionPage", name: "Curated Schumacher Fabric and Wallcovering Showroom", url: `${SITE.url}/schumacher`, about: { "@type": "Brand", name: "Schumacher" }, provider: { "@type": "LocalBusiness", name: SITE.name, telephone: SITE.phone }, hasPart: SCHUMACHER_PRODUCTS.map((p) => ({ "@type": "Product", name: p.name, brand: "Schumacher", category: p.categories.join(" and "), url: `${SITE.url}/schumacher/${p.slug}` })) };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <BreadcrumbJsonLd items={[{ name: "Home", url: SITE.url }, { name: "Luxury Wallcoverings", url: `${SITE.url}/luxury-wallcoverings` }, { name: "Schumacher", url: `${SITE.url}/schumacher` }]} />
    <PageHero eyebrow="Curated Trade Showroom" title="Schumacher Fabric & Wallcovering" subtitle="Explore enduring Schumacher icons selected for Charleston’s historic, coastal and collected interiors. Request a memo, confirm availability and order direct through our studio for the best available pricing." />
    <section className="border-b border-[#e4d9c2] bg-[#f3ead9] px-6 py-16"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1.5fr_1fr]"><div><p className="mb-4 text-xs font-semibold uppercase tracking-[0.3em] text-[#8a6d1d]">Pattern, specified with purpose</p><h2 className="font-serif text-3xl leading-tight text-[#3d2b1f] md:text-4xl">A Schumacher trade partner with installation expertise</h2><p className="mt-5 leading-relaxed text-[#5a4632]">Charleston Decorative Arts helps homeowners, interior designers and architects source Schumacher fabrics and wallpapers with the practical guidance luxury materials require. We coordinate memos, current stock, colorways, quantities, pattern repeats and professional installation—particularly for historic homes, natural materials and Lowcountry conditions.</p></div><div className="border-l border-[#d8c9ae] pl-8"><p className="font-serif text-4xl text-[#8a6d1d]">1889</p><p className="mt-2 text-sm leading-relaxed text-[#5a4632]">Schumacher’s founding year and the beginning of an enduring American decorative legacy.</p><p className="mt-8 font-serif text-4xl text-[#8a6d1d]">Direct</p><p className="mt-2 text-sm leading-relaxed text-[#5a4632]">Order through our trade account with current project pricing confirmed before purchase.</p></div></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-6xl"><div className="mb-10"><p className="mb-3 text-xs font-semibold uppercase tracking-[0.3em] text-[#8a6d1d]">The opening edit</p><h2 className="font-serif text-3xl text-[#3d2b1f] md:text-4xl">Schumacher Icons & Designer Favorites</h2><p className="mt-3 text-sm text-[#5a4632]">Fabric · Wallcovering · Indoor/Outdoor</p></div><div className="grid gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3">{SCHUMACHER_PRODUCTS.map((p, i) => <Link href={`/schumacher/${p.slug}`} key={p.slug} className="group"><div className="relative aspect-[4/5] overflow-hidden bg-[#e9dfcd]"><SchumacherProductImage product={p} priority={i < 3} /></div><h3 className="mt-4 font-serif text-2xl text-[#3d2b1f] group-hover:text-[#8a6d1d]">{p.name}</h3><p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#75604a]">{p.categories.join(" · ")} · {p.styles.join(" · ")}</p></Link>)}</div></div></section>
    <SchumacherInquiry />
    <section className="px-6 pb-24"><div className="mx-auto max-w-3xl"><h2 className="font-serif text-3xl text-[#3d2b1f]">Ordering Schumacher Through CDA</h2><h3 className="mt-8 font-serif text-xl text-[#3d2b1f]">Can I request a Schumacher memo?</h3><p className="mt-2 leading-relaxed text-[#5a4632]">Yes. Tell us the pattern and colorway you are considering. We will coordinate the memo request and help compare it in the room’s actual light.</p><h3 className="mt-7 font-serif text-xl text-[#3d2b1f]">Can CDA check stock and pricing?</h3><p className="mt-2 leading-relaxed text-[#5a4632]">Yes. Schumacher inventory and trade pricing change, so we confirm availability, minimums, freight and the best available project price before ordering.</p><h3 className="mt-7 font-serif text-xl text-[#3d2b1f]">Do you install Schumacher wallcovering?</h3><p className="mt-2 leading-relaxed text-[#5a4632]">Yes. Our services include measuring, quantity review, substrate evaluation, preparation, layout and museum-quality installation throughout Charleston and for selected projects across the Southeast.</p></div></section>
  </>;
}
