export type SchumacherProduct = {
  slug: string;
  name: string;
  categories: ("Fabric" | "Wallcovering")[];
  image?: string;
  itemNumber?: string;
  summary: string;
  rooms: string[];
  styles: string[];
  evidence: string;
};

export const SCHUMACHER_PRODUCTS: SchumacherProduct[] = [
  { slug: "chiang-mai-dragon", name: "Chiang Mai Dragon", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/173272.webp", itemNumber: "173272", summary: "A large-scale dragon and botanical motif for statement rooms, drapery and accent upholstery.", rooms: ["dining rooms", "libraries", "powder rooms"], styles: ["chinoiserie", "statement"], evidence: "Schumacher calls this Art Deco-inspired chinoiserie motif one of its best-loved designs." },
  { slug: "citrus-garden", name: "Citrus Garden", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/175760.webp", itemNumber: "175760", summary: "A lively botanical with citrus fruit and foliage, especially at home in colorful Southern and coastal interiors.", rooms: ["sunrooms", "breakfast rooms", "bedrooms"], styles: ["botanical", "coastal"], evidence: "A 1947 archival Josef Frank print with the color, personality and hand-drawn charm for which the designer is known." },
  { slug: "pyne-hollyhock", name: "Pyne Hollyhock", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/174451.webp", itemNumber: "174451", summary: "A storied chintz associated with Albert Hadley and one of Schumacher’s most sought-after archival designs.", rooms: ["bedrooms", "drawing rooms", "historic homes"], styles: ["chintz", "historic"], evidence: "Schumacher identifies Pyne Hollyhock as one of its most sought-after designs." },
  { slug: "queen-of-spain", name: "Queen of Spain", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5005881.webp", itemNumber: "5005881", summary: "An expressive midcentury motif that brings movement and graphic confidence to traditional or contemporary rooms.", rooms: ["living rooms", "powder rooms", "studies"], styles: ["midcentury", "graphic"], evidence: "Introduced in 1963, this lively painterly pattern remains a fresh example of midcentury design." },
  { slug: "imperial-trellis", name: "Imperial Trellis II", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5005805.webp", itemNumber: "5005805", summary: "An iconic geometric synonymous with Hollywood Regency glamour and crisp architectural rhythm.", rooms: ["entries", "powder rooms", "bedrooms"], styles: ["geometric", "Regency"], evidence: "Schumacher describes Imperial Trellis as an iconic design epitomizing Hollywood Regency glamour." },
  { slug: "birds-and-butterflies", name: "Birds & Butterflies", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/2704420.webp", itemNumber: "2704420", summary: "A celebrated archival design of birds, butterflies and twining foliage, derived from a hand-printed 1960s pattern.", rooms: ["garden rooms", "bedrooms", "nurseries"], styles: ["botanical", "archival"], evidence: "Derived from a hand-printed 1960s wallcovering in Schumacher’s archive." },
  { slug: "lotus-garden", name: "Lotus Garden", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5008430.webp", itemNumber: "5008430", summary: "A lush, layered botanical that makes an immersive statement while remaining rooted in classic decoration.", rooms: ["dining rooms", "bedrooms", "sunrooms"], styles: ["botanical", "traditional"], evidence: "Recreated from a 1920s archival document, this enchanting pattern is an ode to Japanese natural motifs." },
  { slug: "indian-arbre", name: "Indian Arbre", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/175782.webp", itemNumber: "175782", summary: "A refined tree-of-life pattern suited to period-sensitive rooms and collected, globally influenced interiors.", rooms: ["historic homes", "dining rooms", "bedrooms"], styles: ["tree of life", "historic"], evidence: "A lush large-scale floral inspired by traditional palampores and based on a 1920s Schumacher archival document." },
  { slug: "hot-house-flowers", name: "Hot House Flowers", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/174034.webp", itemNumber: "174034", summary: "An exuberant large-scale floral for rooms that call for immersive color and memorable pattern.", rooms: ["powder rooms", "dining rooms", "bedrooms"], styles: ["floral", "statement"], evidence: "A dramatically scaled tree-of-life pattern combining stylized exotic motifs with a modern palette." },
  { slug: "les-gazelles", name: "Les Gazelles Au Bois", categories: ["Fabric"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/68910.webp", itemNumber: "68910", summary: "A sophisticated figural motif with a playful point of view, ideal for jewel-box spaces and distinctive upholstery.", rooms: ["powder rooms", "studies", "entries"], styles: ["figural", "Art Deco"], evidence: "Pierre Pozier’s iconic 1927 design features foliage and leaping gazelles that epitomize Art Deco elegance." },
  { slug: "katsugi", name: "Katsugi", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/2620935.webp", itemNumber: "2620935", summary: "A bold hand-drawn geometric that introduces artisanal energy and a contemporary counterpoint to florals.", rooms: ["living rooms", "bedrooms", "studies"], styles: ["graphic", "artisanal"], evidence: "A Schumacher signature pattern whose painterly design is a whimsical nod to Japanese aesthetics." },
  { slug: "magic-mountain-dragon", name: "Magic Mountain Dragon", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5011591.webp", itemNumber: "5011591", summary: "A fanciful scenic dragon design that turns Schumacher’s decorative exuberance into an immersive wall treatment.", rooms: ["bedrooms", "powder rooms", "nurseries"], styles: ["chinoiserie", "scenic"], evidence: "A newer dragon interpretation offered in fabric and wallcovering." },
  { slug: "antique-ticking-stripe", name: "Antique Ticking Stripe", categories: ["Fabric"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/3475001.webp", itemNumber: "3475001", summary: "A crisp cotton-linen stripe and versatile companion for upholstery, windows and layered rooms.", rooms: ["bedrooms", "living rooms", "porches"], styles: ["stripe", "classic"], evidence: "Schumacher calls this versatile cotton-linen design a classic go-to fabric." },
  { slug: "iconic-leopard", name: "Iconic Leopard", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5007010.webp", itemNumber: "5007010", summary: "A polished animal pattern for chairs, ottomans, pillows and other high-impact accents.", rooms: ["living rooms", "libraries", "bedrooms"], styles: ["animal", "classic"], evidence: "First introduced in the 1970s, this perennial favorite is offered in versatile fabric and wallcovering colorways." },
  { slug: "citrus-garden-indoor-outdoor", name: "Citrus Garden Indoor/Outdoor", categories: ["Fabric"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/177333.webp", itemNumber: "177333", summary: "A performance interpretation of the beloved botanical for Charleston porches, pool houses and family spaces.", rooms: ["porches", "pool houses", "sunrooms"], styles: ["performance", "botanical"], evidence: "Featured by Schumacher among its beloved indoor/outdoor patterns." },
  { slug: "zanzibar-trellis", name: "Zanzibar Trellis", categories: ["Fabric", "Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5006945.webp", itemNumber: "5006945", summary: "An architectural geometric with a sophisticated scale for entries, bedrooms and tailored rooms.", rooms: ["entries", "bedrooms", "studies"], styles: ["geometric", "tailored"], evidence: "Inspired by Elsie de Wolfe’s trellised rooms, this 1970s fretwork pattern has fresh graphic appeal." },
  { slug: "olive", name: "Olive by Rita Konig", categories: ["Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5015920.webp", itemNumber: "5015920", summary: "A fresh traditional wallcovering from Rita Konig with the relaxed character of a well-collected room.", rooms: ["bedrooms", "kitchens", "studies"], styles: ["traditional", "designer collaboration"], evidence: "Part of Schumacher’s Rita Konig collection." },
  { slug: "citrus-blossom-panels", name: "Citrus Blossom Panel Set", categories: ["Wallcovering"], image: "https://cdn-webassets.schumacher.com/catalog/hd-webp/5017162.webp", itemNumber: "5017162", summary: "A mural-like panel set that creates a graceful botanical focal point with fewer visual repeats.", rooms: ["dining rooms", "bedrooms", "entries"], styles: ["panels", "botanical"], evidence: "A panel-format selection for mural-style installations." },
];

export const getSchumacherProduct = (slug: string) =>
  SCHUMACHER_PRODUCTS.find((product) => product.slug === slug);
